[package]
name = "ultrastar-txt"
version = "0.1.0"
authors = ["Robin Nehls <rust@manol.is>"]
description = "A library for parsing and generating Ultrastar TXT files"
license = "MIT"

[dependencies]
regex = "0.2"
lazy_static = "0.2"
